<a href="https://colab.research.google.com/github/shimshimee/class2021Spring/blob/main/%EC%A4%91%EA%B0%84%EB%8C%80%EB%B9%84.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [80]:
class cal: #class = 함수+변수
  def __init__(self): #self = 변수
    self.result = 0
  def add(self, n):
    self.result += n
    return self.result

In [104]:
A = cal() #A = 객체
A.result

0

In [105]:
A.add(4)
A.add(6)

10

In [83]:
import numpy as np #package
n = np.random.randn(100) #randn: 정규분포를 가지는 수

In [ ]:
import matplotlib #folder
import matplotlib.pyplot #module
from matplotlib import pyplot
from matplotlib.pyplot import hist #function

In [101]:
X = np.array([[1,2],[3,4],[5,6]])
X.astype(np.float64) #소수점 있는 숫자로 바꿈
np.zeros_like(X) #전부 0으로 바꿈

array([[0, 0],
       [0, 0],
       [0, 0]])

In [115]:
X = np.ones([2, 3, 4])
Y = X.reshape(6,1,4)
Y

array([[[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]],

       [[1., 1., 1., 1.]]])

In [132]:
arr = np.random.random([8,2,3])
print(type(arr))
print(len(arr)) #가장 큰 list의 개수
print(arr.shape)
print(arr.ndim) #차원
print(arr.size)
print(arr.dtype)

<class 'numpy.ndarray'>
8
(8, 2, 3)
3
48
float64


In [139]:
a = np.arange(1,5)
b = np.arange(9,5,-1)
a = np.matrix(a)
b = np.matrix(b)
print(a)
print(b.T)

[[1 2 3 4]]
[[9]
 [8]
 [7]
 [6]]
